apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: lb-service1
spec:
  host: service1.lb.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash: 
        httpHeaderName: username
