apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2019-02-02T12:29:19Z'
  name: zipkin
  namespace: istio-system
  resourceVersion: '3876745'
  selfLink: /api/v1/namespaces/istio-system/services/zipkin
  uid: 29c49b0b-26e6-11e9-be86-00163e0f555f
spec:
  clusterIP: 172.19.14.149
  ports:
    - name: zipkin-rest
      port: 9411
      protocol: TCP
      targetPort: 9411
  selector:
    app: tracing-on-sls
    component: collector
    jaeger-infra: collector-pod
    release: istio
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
